# Generated by Django 2.2.5 on 2020-02-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0002_auto_20200206_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
