# Generated by Django 2.2.5 on 2020-02-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0004_auto_20200206_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedusers',
            name='org_password',
            field=models.CharField(default='1234', max_length=100),
        ),
    ]
