# Generated by Django 2.2.5 on 2020-02-07 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0005_extendedusers_org_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedusers',
            name='user_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='extendedusers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL),
        ),
    ]
