# Generated by Django 2.2.5 on 2020-02-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0007_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
