# Generated by Django 2.2.5 on 2020-02-18 08:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0008_auto_20200207_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('alias', models.CharField(max_length=100, unique=True)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_in_number', models.IntegerField()),
                ('sem_in_roman', models.CharField(max_length=10)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='alias',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='extendedusers',
            name='sem_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='extendedusers',
            name='updated_on',
            field=models.DateField(default=datetime.date(2020, 2, 18), verbose_name='updated_on'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('alias', models.CharField(max_length=100, unique=True)),
                ('status', models.IntegerField(default=1)),
                ('institute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='amsapp.Institute')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='dept_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='amsapp.Department'),
        ),
    ]
