# Generated by Django 2.2.5 on 2020-02-18 20:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0009_auto_20200218_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='user_semester_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='extendedusers',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='amsapp.Branch'),
        ),
        migrations.AlterField(
            model_name='extendedusers',
            name='sem_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semester', to='amsapp.Semester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extendedusers',
            name='updated_on',
            field=models.DateField(default=datetime.date(2020, 2, 19), verbose_name='updated_on'),
        ),
    ]
