# Generated by Django 2.2.5 on 2020-02-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amsapp', '0010_auto_20200219_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedusers',
            name='disp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
